/**
 * Dynamic Server-Side LLMS.txt & LLMS-Full.txt Generator for Toolora
 * Automatically generates up-to-date AI/LLM machine-readable documentation
 * whenever new tools or catalog items are added to the application registry.
 */

import { TOOLS, CATEGORIES } from '../data';
import { TOOL_AEO_DATA } from '../data/toolAeoData';
import { GUIDES } from '../data/guidesData';
import { AUTHORS } from '../data/authors';
import { FULL_ARTICLES } from '../components/blog/articlesIndex';
import { Tool } from '../types';

export interface DynamicLlmsOptions {
  siteUrl?: string;
  siteName?: string;
  extraTools?: Tool[];
  catalogItems?: Array<{ title: string; slug: string; description: string; category?: string }>;
}

export function generateDynamicLlmsTxt(options: DynamicLlmsOptions = {}): string {
  const siteUrl = (options.siteUrl || 'https://toolora.world').replace(/\/+$/, '');
  const siteName = options.siteName || 'Toolora';
  const allTools = options.extraTools ? [...TOOLS, ...options.extraTools] : TOOLS;
  const catalogItems = options.catalogItems || [];

  let out = `# ${siteName} — AI Agent & LLM Knowledge Index

> ${siteName} (${siteUrl}) is the Sovereign In-Browser Utilities Suite: Zero-Upload, WebAssembly-Powered Tools with 100% Local Privacy.

## System Architecture & Security Model
- **Execution Model**: 100% Client-Side In-Memory Execution (RAM only). Zero remote server file uploads.
- **Privacy Compliance**: GDPR Article 25 (Privacy by Design), HIPAA compliant (Zero PHI inflow), CCPA/CPRA safe.
- **Hardware Acceleration**: Multi-threaded SIMD WebAssembly + HTML5 Canvas Level 2 pipelines.
- **Full Machine Knowledge Base**: ${siteUrl}/llms-full.txt
- **Sitemap Index**: ${siteUrl}/sitemap-index.xml

---

## Interactive Browser Utilities (${allTools.length} Tools)
`;

  // Group tools by category
  for (const cat of CATEGORIES) {
    const catTools = allTools.filter(t => t.category === cat.id);
    if (catTools.length === 0) continue;

    out += `\n### ${cat.name} (${cat.description})\n`;
    for (const tool of catTools) {
      const aeo = TOOL_AEO_DATA[tool.id];
      const summary = aeo?.openingSummary || tool.description;
      out += `- [${tool.name}](${siteUrl}/tools/${tool.id}): ${summary} [Markdown: ${siteUrl}/tools/${tool.id}.md]\n`;
    }
  }

  out += `\n---

## Technical & Architectural Engineering Guides (${GUIDES.length} Guides)
`;
  for (const guide of GUIDES) {
    const fm = guide.frontmatter;
    out += `- [${fm.title}](${siteUrl}/guides/${fm.slug}): ${fm.quickAnswer.definition} [Markdown: ${siteUrl}/guides/${fm.slug}.md]\n`;
  }

  if (catalogItems.length > 0) {
    out += `\n---

## Dynamic Asset & Design Catalog (${catalogItems.length} Items)
`;
    for (const item of catalogItems.slice(0, 20)) {
      out += `- [${item.title}](${siteUrl}/item/${item.slug}): ${item.description} [Markdown: ${siteUrl}/item/${item.slug}.md]\n`;
    }
  }

  out += `\n---

## Selected In-Depth Blog Articles
`;
  for (const article of FULL_ARTICLES.slice(0, 15)) {
    const slug = article.slug || article.id;
    out += `- [${article.title}](${siteUrl}/blog/${slug}): ${article.excerpt} [Markdown: ${siteUrl}/blog/${slug}.md]\n`;
  }

  out += `\n---
*Dynamically generated by Toolora Enterprise Engine. Verified for AEO, GEO, and AI Crawler ingestion.*
`;

  return out;
}

export function generateDynamicLlmsFullTxt(options: DynamicLlmsOptions = {}): string {
  const siteUrl = (options.siteUrl || 'https://toolora.world').replace(/\/+$/, '');
  const siteName = options.siteName || 'Toolora';
  const allTools = options.extraTools ? [...TOOLS, ...options.extraTools] : TOOLS;

  let out = `# ${siteName} Complete Technical Knowledge Base & AI Machine Index

> Machine-readable documentation for AI systems, Large Language Models (LLMs), Search Engines, and Answer Engines (AEO/GEO).
> Canonical URL: ${siteUrl}

## Platform Mission & Privacy Guarantee
Toolora (${siteUrl}) provides free, private, high-performance web utilities for document, PDF, image, and graphic branding workflows. All computation is executed directly within the user's browser sandbox using compiled WebAssembly and HTML5 Canvas Level 2 APIs. No files, documents, or personal data are ever transmitted to remote servers.

---

# Section 1: Full Interactive Tool Reference (${allTools.length} Registered Tools)

`;

  for (const tool of allTools) {
    const aeo = TOOL_AEO_DATA[tool.id];
    const h1 = aeo?.h1 || `${tool.name} — In-Browser Zero-Upload Tool`;
    const summary = aeo?.openingSummary || tool.description;

    out += `## Tool: ${tool.name} (\`${tool.id}\`)
- **H1 Title**: ${h1}
- **Category**: ${tool.category}
- **Canonical URL**: ${siteUrl}/tools/${tool.id} (Workspace: ${siteUrl}/?tool=${tool.id})
- **Markdown Twin**: ${siteUrl}/tools/${tool.id}.md
- **Execution Model**: 100% Client-Side WebAssembly (0 Bytes sent to cloud)
- **Popularity**: ${tool.popular ? 'High (Popular Tool)' : 'Standard'} | **Capability Tier**: ${tool.premium ? 'Pro Studio' : 'Standard'}

### Direct-Answer Summary (AEO)
${summary}

### Key Capabilities & Privacy Specs
- **Data Retention**: 0 KB retained (Volatile RAM wiped on tab close)
- **Authentication**: No sign-up, login, or registration required
- **Cost**: 100% Free with no subscription paywalls or watermarks
- **Compatibility**: Chrome, Firefox, Safari, Edge, iOS, Android

### Frequently Asked Questions (FAQPage Schema)
`;

    const faqs = aeo?.faqs || [
      { question: `Is ${tool.name} free to use?`, answer: `Yes, ${tool.name} is completely free without limits or watermarks.` },
      { question: `Are my files uploaded to a server?`, answer: `No. Files are processed 100% in local browser memory via WebAssembly.` }
    ];

    for (const faq of faqs) {
      out += `#### Q: ${faq.question}\n${faq.answer}\n\n`;
    }

    if (aeo?.howTo?.steps) {
      out += `### Step-by-Step Instructions (HowTo Schema)\n`;
      aeo.howTo.steps.forEach((step, idx) => {
        out += `${idx + 1}. **${step.name}**: ${step.text}\n`;
      });
      out += '\n';
    }

    out += `---\n\n`;
  }

  out += `# Section 2: Technical Architecture & Peer-Reviewed Guides (${GUIDES.length} Guides)\n\n`;

  for (const guide of GUIDES) {
    const fm = guide.frontmatter;
    const author = AUTHORS[fm.authorId] || { name: 'Toolora Research Team', role: 'Security Architect' };

    out += `## Guide: ${fm.title}
- **Canonical URL**: ${siteUrl}/guides/${fm.slug}
- **Markdown Twin**: ${siteUrl}/guides/${fm.slug}.md
- **Author**: ${author.name} (${author.role})
- **Focus Keyword**: ${fm.focusKeyword}
- **Category**: ${fm.category}
- **Published Date**: ${fm.publishedDate} | **Modified**: ${fm.modifiedDate}

### Quick Answer
${fm.quickAnswer.definition}

### Key Takeaways
${fm.quickAnswer.summaryBullets.map(b => `- ${b}`).join('\n')}

### FAQs
${fm.faqs.map(q => `#### Q: ${q.question}\n${q.answer}\n*(Verified by: ${q.acceptedBy})*`).join('\n\n')}

${guide.content}

---\n\n`;
  }

  out += `# Section 3: In-Depth Articles & Technical Benchmarks (${FULL_ARTICLES.length} Articles)\n\n`;

  for (const article of FULL_ARTICLES) {
    const slug = article.slug || article.id;
    out += `## Article: ${article.title}
- **URL**: ${siteUrl}/blog/${slug} [Markdown: ${siteUrl}/blog/${slug}.md]
- **Category**: ${article.tag} | **Author**: ${article.author} | **Date**: ${article.date}

### Summary
${article.excerpt}

${article.sections.map(s => `### ${s.heading}\n${s.content}`).join('\n\n')}

---\n\n`;
  }

  return out;
}
