import { Tool } from './types';

export const TOOLS: Tool[] = [
  // --- PDF TOOLS ---
  {
    id: 'pdf-editor',
    name: 'Interactive PDF Editor',
    description: 'Import any PDF, type text anywhere over sheets, sketch freehand, stamp signatures, and export final layers natively.',
    category: 'pdf',
    icon: 'PenTool',
    popular: true,
    premium: true,
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Merge multiple PDF documents into a single cohesive PDF file natively in your browser.',
    category: 'pdf',
    icon: 'MergeField',
    popular: true,
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Extract specific pages or split a PDF into separate files easily with exact ranges.',
    category: 'pdf',
    icon: 'Scissors',
    popular: false,
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size while maintaining pristine text and image scale and readability.',
    category: 'pdf',
    icon: 'Minimize2',
    popular: true,
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages into high-resolution JPG or PNG assets instantly.',
    category: 'pdf',
    icon: 'FileImage',
    popular: false,
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert PNG, JPG, WebP images to highly organized PDF documents.',
    category: 'pdf',
    icon: 'Image',
    popular: true,
  },
  {
    id: 'pdf-lock-unlock',
    name: 'PDF Lock & Unlock',
    description: 'Secure your files with a secure password or instantly unlock password-protected PDFs.',
    category: 'pdf',
    icon: 'Lock',
    popular: false,
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF Pages',
    description: 'Rotate individual pages or the entire document and download the perfectly re-oriented PDF.',
    category: 'pdf',
    icon: 'RotateCw',
    popular: false,
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Stamps custom text or image watermarks with precise size, angle, and transparency values inline.',
    category: 'pdf',
    icon: 'Droplet',
    popular: true,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Decompile secure metadata streams and pages to extract raw readable plain text cleanly.',
    category: 'pdf',
    icon: 'FileText',
    popular: false,
  },
  {
    id: 'pdf-toolbox',
    name: 'PDF Toolbox (Merge & Split)',
    description: 'Comprehensive in-browser PDF workspace to merge multiple documents, extract page ranges, split, or rotate pages using pdf-lib.',
    category: 'pdf',
    icon: 'Boxes',
    popular: true,
    premium: true,
  },

  // --- IMAGE TOOLS ---
  {
    id: 'image-optimizer',
    name: 'Canvas Image Optimizer',
    description: 'Resize pixel dimensions and convert image formats like PNG to WebP with hardware-accelerated Canvas API processing.',
    category: 'image',
    icon: 'Sparkles',
    popular: true,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress PNG, JPEG, or WebP images by scale and quality without losing design detail.',
    category: 'image',
    icon: 'Shrink',
    popular: true,
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Change image dimensions based on aspect ratios, custom width, or specific height targets.',
    category: 'image',
    icon: 'AspectRatio',
    popular: false,
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert and save images to PNG, JPEG, WebP, GIF, or BMP format instantly.',
    category: 'image',
    icon: 'RefreshCw',
    popular: true,
  },
  {
    id: 'ocr-tool',
    name: 'Image to Text (OCR)',
    description: 'Extract raw selectable text from diagrams, screenshots, or documents using local OCR.',
    category: 'image',
    icon: 'TextCursor',
    popular: true,
    premium: true,
  },
  {
    id: 'image-editor',
    name: 'Prism Image Editor',
    description: 'Fine-tune crop, rotate, and apply vintage/slate filters, brightness, and contrast curves inline.',
    category: 'image',
    icon: 'SlidersHorizontal',
    popular: true,
  },
  {
    id: 'passport-photo-maker',
    name: 'Passport Photo Maker',
    description: 'Standardize photo layouts for visas, passports, or IDs of size 2x2\" and print grid sheets.',
    category: 'image',
    icon: 'UserSquare',
    popular: false,
  },
  {
    id: 'bg-remover',
    name: 'Smart Backdrop Eraser',
    description: 'Erase or swap colors or simple background backdrops using client-side chroma isolation.',
    category: 'image',
    icon: 'Eraser',
    popular: false,
  },

  // --- DOCUMENTS & GENERATORS ---
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Generate stunning billing statements with rich items, taxes, and high-style editorial sheets.',
    category: 'document',
    icon: 'ReceiptCombined',
    popular: true,
    premium: true,
  },
  {
    id: 'resume-cv-builder',
    name: 'Resume & CV Builder',
    description: 'Build professional tech or creative resumes with beautiful custom grid systems and text controls.',
    category: 'document',
    icon: 'FileText',
    popular: true,
    premium: true,
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate premium custom QR vectors for URLs, WiFi hotspots, text content, and vCards.',
    category: 'document',
    icon: 'QrCode',
    popular: true,
  },
  {
    id: 'signature-maker',
    name: 'Signature Studio',
    description: 'Draw freehand or type sleek cursives to create beautiful transparent PNG e-signatures.',
    category: 'document',
    icon: 'Signature',
    popular: false,
  },
  {
    id: 'business-card-gen',
    name: 'Business Card Designer',
    description: 'Design professional networking double-sided business cards in modern typography layouts.',
    category: 'document',
    icon: 'Contact',
    popular: false,
  },
  {
    id: 'certificate-maker',
    name: 'Certificate & Award Designer',
    description: 'Instantly design professional certificates for educational, training, or appreciation achievements.',
    category: 'document',
    icon: 'Award',
    popular: false,
  },
  {
    id: 'mockup-gen',
    name: 'Mockup Studio Pro',
    description: 'Create high fidelity 2D/3D brand showcases on custom apparel, ceramic mugs, flasks, and cards inline.',
    category: 'document',
    icon: 'Sparkles',
    popular: true,
    premium: true,
  },
  {
    id: 'bill-form-gen',
    name: 'Bill & Form Ledger',
    description: 'Produce fully editable utility billing statements, retail supermarket receipts, and Customs M9 cards.',
    category: 'document',
    icon: 'FileText',
    popular: true,
    premium: true,
  },

  // --- OTHER ---
  {
    id: 'unit-converter',
    name: 'Universal Unit Converter',
    description: 'Effortlessly swap lengths, volumes, speeds, temperatures, and data capacities interactively.',
    category: 'other',
    icon: 'Gauge',
    popular: false,
  },
  {
    id: 'currency-converter',
    name: 'Real-time Currency Converter',
    description: 'Convert between popular world currencies with high-accuracy rates.',
    category: 'other',
    icon: 'Coins',
    popular: false,
  },
  {
    id: 'text-tools',
    name: 'Advanced Text Suite',
    description: 'Perform word count analysis, case transformation, lorem ipsum placeholder generation, and text diff comparison.',
    category: 'other',
    icon: 'WrapText',
    popular: false,
  }
];

export const CATEGORIES = [
  { id: 'all', name: 'All Tools', description: 'Browse our complete catalog of private offline tools.' },
  { id: 'pdf', name: 'PDF Suite', description: 'Modify, secure, merge, or convert PDF files safely in-browser.' },
  { id: 'image', name: 'Image Studio', description: 'Compress, resize, edit, or extract text from graphics instantly.' },
  { id: 'document', name: 'Documents & Certificates', description: 'Draft elegant invoices, resumes, QR stamps, and signatures.' },
  { id: 'other', name: 'Converters & Text Utilities', description: 'Convert weights, calculate exchange counters, and refine copywriting text.' }
];

export const SUGGESTED_SEARCHES = [
  'Merge PDF',
  'Invoice Generator',
  'Image to Text',
  'E-Signature Maker',
  'QR WiFi Code',
  'Resume CV Builder',
  'Image Compressor'
];
